version: '3.9'

services:
  backend:
    depends_on:
      - database
    build: ./backend
    volumes:
      - ./backend:/back
    container_name: blitzTrybe-backend
    ports:
      - 3001:3001
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=tutu
      - MYSQL_DATABASE=blitzTrybe
      - HOST=localhost
      - JWT_SECRET=seusecretdetoken
    tty: true
    stdin_open: true
   
  database:
    image: mysql:5.7
    container_name: blitzTrybe-bd
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=tutu
      - MYSQL_DATABASE=blitzTrybe
