DROP DATABASE IF EXISTS blitzTrybe;

CREATE DATABASE blitzTrybe;

USE blitzTrybe;

CREATE TABLE Users (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  is_admin BOOLEAN NOT NULL,
  email VARCHAR(100) NOT NULL,
  github VARCHAR(100) NOT NULL,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE Tasks (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  user_id INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES Users(`id`)
);

SET SQL_SAFE_UPDATES = 0;
